version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: zailex/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    
  vproapp:
    build:
      context: ./Docker-files/app
    image: zailex/vprofileapp
    container_name: vprodapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/user/local/tomcat/webapps
    
  vproweb:
    build:
      context: ./Docker-files/web
    image: zailex/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
    
volumes:
  vprodbdata: {}
  vproappdata: {}
  